// Subdivisions (England, Scotland, Wales no tienen código ISO propio)
const SPECIAL: Record<string, string> = {
  'England': 'gb-eng',
  'Scotland': 'gb-sct',
  'Wales': 'gb-wls',
}

// Nombre de equipo → código ISO 3166-1 alpha-2
const ISO2: Record<string, string> = {
  'Mexico': 'MX', 'United States': 'US', 'Canada': 'CA',
  'Brazil': 'BR', 'Argentina': 'AR', 'Uruguay': 'UY', 'Colombia': 'CO',
  'Ecuador': 'EC', 'Chile': 'CL', 'Peru': 'PE', 'Paraguay': 'PY',
  'Venezuela': 'VE', 'Bolivia': 'BO', 'Suriname': 'SR',
  'Spain': 'ES', 'France': 'FR', 'Germany': 'DE', 'Portugal': 'PT',
  'Netherlands': 'NL', 'Belgium': 'BE', 'Croatia': 'HR', 'Serbia': 'RS',
  'Switzerland': 'CH', 'Poland': 'PL', 'Turkey': 'TR', 'Austria': 'AT',
  'Ukraine': 'UA', 'Hungary': 'HU', 'Denmark': 'DK', 'Sweden': 'SE',
  'Norway': 'NO', 'Czech Republic': 'CZ', 'Slovakia': 'SK', 'Romania': 'RO',
  'Greece': 'GR', 'Albania': 'AL', 'North Macedonia': 'MK', 'Slovenia': 'SI',
  'Bosnia and Herzegovina': 'BA', 'Montenegro': 'ME', 'Georgia': 'GE',
  'Finland': 'FI', 'Iceland': 'IS', 'Ireland': 'IE', 'Israel': 'IL',
  'Luxembourg': 'LU', 'Moldova': 'MD', 'Armenia': 'AM', 'Azerbaijan': 'AZ',
  'Kazakhstan': 'KZ', 'Uzbekistan': 'UZ',
  'Japan': 'JP', 'South Korea': 'KR', 'Saudi Arabia': 'SA', 'Iran': 'IR',
  'Australia': 'AU', 'China': 'CN', 'Qatar': 'QA', 'Iraq': 'IQ',
  'Jordan': 'JO', 'Bahrain': 'BH', 'Oman': 'OM', 'Kuwait': 'KW',
  'UAE': 'AE', 'United Arab Emirates': 'AE', 'Palestine': 'PS',
  'Vietnam': 'VN', 'Thailand': 'TH', 'Indonesia': 'ID', 'Philippines': 'PH',
  'Malaysia': 'MY', 'India': 'IN', 'Pakistan': 'PK',
  'New Zealand': 'NZ', 'Papua New Guinea': 'PG', 'Fiji': 'FJ',
  'New Caledonia': 'NC', 'Tahiti': 'PF',
  'Morocco': 'MA', 'Senegal': 'SN', 'Nigeria': 'NG', 'Cameroon': 'CM',
  'Ghana': 'GH', 'Egypt': 'EG', 'South Africa': 'ZA', 'Algeria': 'DZ',
  'Tunisia': 'TN', 'Mali': 'ML', 'Guinea': 'GN', 'Guinea-Bissau': 'GW',
  "Côte d'Ivoire": 'CI', 'Ivory Coast': 'CI', 'Burkina Faso': 'BF',
  'Cape Verde': 'CV', 'DR Congo': 'CD', 'Congo DR': 'CD',
  'Sierra Leone': 'SL', 'Equatorial Guinea': 'GQ', 'Benin': 'BJ',
  'Tanzania': 'TZ', 'Zambia': 'ZM', 'Zimbabwe': 'ZW', 'Kenya': 'KE',
  'Uganda': 'UG', 'Rwanda': 'RW', 'Ethiopia': 'ET', 'Angola': 'AO',
  'Mozambique': 'MZ', 'Namibia': 'NA', 'Mauritania': 'MR', 'Libya': 'LY',
  'Sudan': 'SD',
  'Costa Rica': 'CR', 'Panama': 'PA', 'Jamaica': 'JM', 'Honduras': 'HN',
  'Guatemala': 'GT', 'El Salvador': 'SV', 'Haiti': 'HT', 'Cuba': 'CU',
  'Trinidad and Tobago': 'TT', 'Dominican Republic': 'DO',
  'Nicaragua': 'NI', 'Curacao': 'CW',
}

// Inglés → Español
const ES: Record<string, string> = {
  'Mexico': 'México',
  'United States': 'Estados Unidos',
  'Brazil': 'Brasil',
  'France': 'Francia',
  'Germany': 'Alemania',
  'England': 'Inglaterra',
  'Scotland': 'Escocia',
  'Wales': 'Gales',
  'Netherlands': 'Países Bajos',
  'Belgium': 'Bélgica',
  'Switzerland': 'Suiza',
  'Poland': 'Polonia',
  'Turkey': 'Turquía',
  'Hungary': 'Hungría',
  'Denmark': 'Dinamarca',
  'Sweden': 'Suecia',
  'Norway': 'Noruega',
  'Czech Republic': 'República Checa',
  'Slovakia': 'Eslovaquia',
  'Romania': 'Rumanía',
  'Greece': 'Grecia',
  'North Macedonia': 'Macedonia del Norte',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Finland': 'Finlandia',
  'Iceland': 'Islandia',
  'Ireland': 'Irlanda',
  'Slovenia': 'Eslovenia',
  'Georgia': 'Georgia',
  'Armenia': 'Armenia',
  'Azerbaijan': 'Azerbaiyán',
  'Kazakhstan': 'Kazajistán',
  'Uzbekistan': 'Uzbekistán',
  'Japan': 'Japón',
  'South Korea': 'Corea del Sur',
  'Saudi Arabia': 'Arabia Saudita',
  'Iran': 'Irán',
  'Australia': 'Australia',
  'Qatar': 'Catar',
  'Iraq': 'Irak',
  'Jordan': 'Jordania',
  'Bahrain': 'Baréin',
  'Oman': 'Omán',
  'Palestine': 'Palestina',
  'Vietnam': 'Vietnam',
  'Thailand': 'Tailandia',
  'Philippines': 'Filipinas',
  'New Zealand': 'Nueva Zelanda',
  'Papua New Guinea': 'Papúa Nueva Guinea',
  'New Caledonia': 'Nueva Caledonia',
  'Morocco': 'Marruecos',
  'Cameroon': 'Camerún',
  'Egypt': 'Egipto',
  'South Africa': 'Sudáfrica',
  'Algeria': 'Argelia',
  'Tunisia': 'Túnez',
  'Guinea-Bissau': 'Guinea-Bisáu',
  "Côte d'Ivoire": 'Costa de Marfil',
  'Ivory Coast': 'Costa de Marfil',
  'DR Congo': 'R. D. del Congo',
  'Congo DR': 'R. D. del Congo',
  'Sierra Leone': 'Sierra Leona',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  'Cape Verde': 'Cabo Verde',
  'Mauritania': 'Mauritania',
  'Panama': 'Panamá',
  'Haiti': 'Haití',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'Dominican Republic': 'Rep. Dominicana',
  'Peru': 'Perú',
  'Suriname': 'Surinam',
}

export function translateTeam(name: string): string {
  return ES[name] ?? name
}

// Devuelve la URL de la bandera en flagcdn.com (40px de ancho)
export function flagUrlForTeam(name: string): string | null {
  const special = SPECIAL[name]
  if (special) return `https://flagcdn.com/w40/${special}.png`
  const iso = ISO2[name]
  return iso ? `https://flagcdn.com/w40/${iso.toLowerCase()}.png` : null
}
